[default]
extend-ignore-identifiers-re = [
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# words that should not be corrected
O957 = "O957"
dot_acn = ".acn"
dot_fot = ".fot"
dot_ist = ".ist"
MOR = "MOR"
strat = "strat"
nam = "nam"

[files]
extend-exclude = [
    ".gitignore", 
    ".pre-commit-config.yaml", 
    "./.github/ISSUE_TEMPLATE/general_issue.md"
]
