collection_name = "Torres Paleontology Research Lab"
institution = "University of Montana"
curator = "Dr. Michael Torres"
email = "torres.paleo@example.edu"
phone = "(555) 123-4567"
specialization = "Mesozoic vertebrates & paleoecology"
collection_size = "15,000+ specimens"
geographic_focus = "Western North America"
website = "paleontology.example.edu/torres-lab"
established = "2018"
research_interests = "Dinosaur diversity, extinction events"
