expedition_name = "Hell Creek Formation Survey 2023"
expedition_code = "HCF-2023"
principal_investigator = "Dr. Michael Torres"
dates = "June 15 - July 20, 2023"
location = "Garfield County, Montana"
objectives = "Late Cretaceous vertebrate diversity study"
team_size = "8 researchers, 4 graduate students"
permits = "BLM Permit #MT-2023-PAL-034"
weather_conditions = "Hot, dry; daily temps 85-95°F"
total_specimens = "127 catalogued specimens"
significant_finds = "Partial T. rex dentary, complete turtle shell"
funding = "NSF Grant #EAR-2023456"
