locality_name = "Dinosaur National Monument Quarry"
locality_number = "DINO-2023-007"
coordinates = "40.4481°N, 109.2989°W"
elevation = "1,478 m"
formation = "Morrison Formation"
member = "Brushy Basin Member"
age = "Late Jurassic (Tithonian)"
lithology = "Sandstone and mudstone"
depositional_environment = "Fluvial channel deposits"
fossils_found = "Allosaurus, Camarasaurus, Stegosaurus"
access_notes = "4WD required, seasonal road closure Oct-May"
land_ownership = "National Park Service"
