plate_number = "Plate VII"
figure_range = "Figures 1-6"
specimens_figured = "USNM PAL 456789, 456790, 456791"
scientific_names = "Anomalocaris canadensis"
views_shown = "Lateral, dorsal, ventral, detail of appendages"
scale_bars = "1 cm (figs 1-3), 5 mm (figs 4-6)"
photography_by = "Dr. Sarah Mitchell"
preparation = "Coated with ammonium chloride sublimate"
repository = "Smithsonian Institution"
publication = "Journal of Paleontology, Vol. 97, 2023"
