block_id = "MOR-001-B"
specimen_count = "3 individuals"
taxa_present = "Maiasaura peeblesorum (2), Triceratops horridus (1)"
formation = "Two Medicine Formation"
member = "Upper Member"
age = "Late Cretaceous (Campanian)"
locality = "Egg Mountain, Montana"
coordinates = "47.6062°N, 112.6400°W"
matrix = "Mudstone with calcite concretions"
preservation = "Disarticulated, 60% complete"
field_notes = "Bone bed assemblage, likely death assemblage"
