catalog_number = "USNM PAL 123456"
scientific_name = "Trilobita indet."
common_name = "Trilobite"
formation = "Burgess Shale"
age = "Middle Cambrian"
locality = "Walcott Quarry, British Columbia"
collected_by = "C.D. Walcott"
date_collected = "1909-08-15"
preparation = "Mechanical prep, latex cast"
condition = "Complete, articulated"
repository = "National Museum of Natural History"
