kingdom = "Animalia"
phylum = "Arthropoda"
class = "Trilobita"
order = "Redlichiida"
family = "Olenellidae"
genus = "Olenellus"
species = "gilberti"
author = "Meek, 1874"
common_name = "Gilbert's Trilobite"
type_status = "Holotype"
synonyms = "Paradoxides gilberti Meek, 1874"
