font_name = "Times-Roman"
font_size = 14
key_color_r = 0.2
key_color_g = 0.2
key_color_b = 0.2
value_color_r = 0.0
value_color_g = 0.0
value_color_b = 0.0
padding_percent = 0.04
width_inches = 2.5
height_inches = 3.0
bold_keys = true
bold_values = false
italic_keys = false
italic_values = false
show_keys = true
show_values = false
