font_name = "Helvetica"
font_size = 12
key_color_r = 0.0
key_color_g = 0.0
key_color_b = 0.0
value_color_r = 0.0
value_color_g = 0.0
value_color_b = 1.0
padding_percent = 0.06
width_inches = 3.0
height_inches = 2.0
bold_keys = false
bold_values = true
italic_keys = false
italic_values = false
show_keys = false
show_values = true
