font_name = "Helvetica"
font_size = 10
key_color_r = 0.0
key_color_g = 0.0
key_color_b = 0.0
value_color_r = 1.0
value_color_g = 0.0
value_color_b = 0.0
padding_percent = 0.08
width_inches = 4.0
height_inches = 2.5
bold_keys = true
bold_values = false
italic_keys = false
italic_values = true
